import { onCall, HttpsError } from 'firebase-functions/v2/https';
import * as admin from 'firebase-admin';

/**
 * Datos del historial de partidos de un jugador para su perfil.
 *
 * Port de `getPlayerEvaluationsAction` (src/lib/actions/evaluation-actions.ts:358)
 * más el armado que la web hace en el cliente dentro de
 * `player-match-debrief-view.tsx` (líneas 515-577).
 *
 * Dos diferencias deliberadas respecto a la web:
 *
 * 1. Devuelve TODO en una sola llamada (evaluaciones + partidos + historial de
 *    OVR + autoevaluaciones). La web las pide por separado desde el navegador:
 *    un getDoc por partido más un getDocs por partido para las autoevaluaciones.
 *    En un celular con mala señal ese N+1 se nota.
 *
 * 2. El enmascarado de identidad pasa a ser real. La web lo hace en una server
 *    action, pero `evaluations` tiene lectura abierta a cualquier autenticado
 *    en firestore.rules, así que el cliente podía leer `evaluatorId` directo y
 *    saltearse el enmascarado. Acá la lógica es la misma, pero el cliente móvil
 *    nunca ve el dato crudo.
 */

const MAX_MATCHES = 20;

function requireAuth(request: { auth?: { uid: string } | null }): string {
  if (!request.auth) throw new HttpsError('unauthenticated', 'Debés iniciar sesión.');
  return request.auth.uid;
}

/**
 * Oculta quién evaluó, salvo que corresponda mostrarlo.
 * Mismas cuatro condiciones que la web, en el mismo orden.
 */
function maskEvaluation(ev: any, requesterId: string): any {
  if (ev.identityRevealed) return ev;
  if (ev.evaluatorId === requesterId) return ev;
  if (ev.autoGenerated || ev.evaluatorId === 'AI') return ev;

  const { evaluatorId, evaluatorDisplayName, evaluatorPhotoUrl, ...rest } = ev;
  return { ...rest, evaluatorId: 'anonymous', isAnonymous: true };
}

export const getPlayerEvaluations = onCall({ region: 'us-central1' }, async (request) => {
  const requesterId = requireAuth(request);
  const playerId = String(request.data?.playerId ?? '');
  if (!playerId) throw new HttpsError('invalid-argument', 'Falta playerId.');

  const db = admin.firestore();

  const evalsSnap = await db
    .collection('evaluations')
    .where('playerId', '==', playerId)
    .orderBy('evaluatedAt', 'desc')
    .limit(MAX_MATCHES)
    .get();

  if (evalsSnap.empty) {
    return { ok: true, matches: [] };
  }

  const evaluations = evalsSnap.docs.map((d) => maskEvaluation({ id: d.id, ...d.data() }, requesterId));

  // Agrupar por partido, conservando el orden (evaluatedAt desc).
  const byMatch = new Map<string, any[]>();
  for (const ev of evaluations) {
    if (!ev.matchId) continue;
    if (!byMatch.has(ev.matchId)) byMatch.set(ev.matchId, []);
    byMatch.get(ev.matchId)!.push(ev);
  }
  const matchIds = [...byMatch.keys()];

  // Partidos, autoevaluaciones e historial de OVR, todo en paralelo.
  const [matchDocs, selfEvalSnaps, ovrHistorySnap] = await Promise.all([
    db.getAll(...matchIds.map((id) => db.collection('matches').doc(id))),
    Promise.all(
      matchIds.map((matchId) =>
        db
          .collection('matches')
          .doc(matchId)
          .collection('selfEvaluations')
          .where('playerId', '==', playerId)
          .limit(1)
          .get()
      )
    ),
    db.collection('players').doc(playerId).collection('ovrHistory').get(),
  ]);

  const matchesById = new Map(matchDocs.filter((d) => d.exists).map((d) => [d.id, d.data()!]));

  const selfEvalByMatch = new Map<string, any>();
  matchIds.forEach((matchId, i) => {
    const snap = selfEvalSnaps[i];
    if (!snap.empty) {
      const d = snap.docs[0];
      selfEvalByMatch.set(matchId, { id: d.id, ...d.data() });
    }
  });

  const ovrByMatch = new Map<string, any>();
  ovrHistorySnap.docs.forEach((d) => {
    const data = d.data();
    if (data.matchId) ovrByMatch.set(data.matchId, data);
  });

  const matches = matchIds
    .map((matchId) => {
      const m = matchesById.get(matchId);
      if (!m) return null;
      return {
        matchId,
        title: m.title ?? 'Partido',
        date: m.date ?? null,
        time: m.time ?? null,
        type: m.type ?? null,
        status: m.status ?? null,
        locationName: m.location?.address ?? m.location?.name ?? null,
        peerEvaluations: byMatch.get(matchId) ?? [],
        selfEvaluation: selfEvalByMatch.get(matchId) ?? null,
        ovrHistory: ovrByMatch.get(matchId) ?? null,
      };
    })
    .filter((m): m is NonNullable<typeof m> => m !== null);

  return { ok: true, matches };
});
