// Modelos del historial de partidos de un jugador.
//
// Port de los tipos que arma `player-match-debrief-view.tsx` en la web, pero
// alimentados por la Cloud Function `getPlayerEvaluations`, que devuelve todo
// junto y ya con la identidad de los evaluadores enmascarada.

class AttributeChange {
  final String attribute;
  final int change;

  const AttributeChange({required this.attribute, required this.change});

  factory AttributeChange.fromMap(Map<String, dynamic> m) => AttributeChange(
        attribute: (m['attribute'] ?? '').toString(),
        change: (m['change'] as num?)?.toInt() ?? 0,
      );
}

class EvaluationTag {
  final String id;
  final String name;
  final String impact; // 'positive' | 'negative'
  final List<AttributeChange> effects;

  const EvaluationTag({
    required this.id,
    required this.name,
    required this.impact,
    this.effects = const [],
  });

  factory EvaluationTag.fromMap(Map<String, dynamic> m) => EvaluationTag(
        id: (m['id'] ?? '').toString(),
        name: (m['name'] ?? '').toString(),
        impact: (m['impact'] ?? 'positive').toString(),
        effects: ((m['effects'] as List?) ?? const [])
            .whereType<Map>()
            .map((e) => AttributeChange.fromMap(Map<String, dynamic>.from(e)))
            .toList(),
      );
}

/// Los cuatro tipos de evaluación, en el mismo orden de precedencia que
/// `getEvalType` en la web (player-match-debrief-view.tsx:86).
enum EvalType { points, tags, text, auto }

class PeerEvaluation {
  final String id;
  final String evaluatorId;
  final String? evaluatorDisplayName;
  final String? evaluatorPhotoUrl;
  final bool isAnonymous;
  final bool autoGenerated;
  final bool identityRevealed;
  final String? identityRequestStatus;
  final double? rating;
  final List<EvaluationTag> performanceTags;
  final String? textDescription;
  final String? aiSummary;
  final List<AttributeChange> aiAttributeChanges;

  const PeerEvaluation({
    required this.id,
    required this.evaluatorId,
    this.evaluatorDisplayName,
    this.evaluatorPhotoUrl,
    this.isAnonymous = false,
    this.autoGenerated = false,
    this.identityRevealed = false,
    this.identityRequestStatus,
    this.rating,
    this.performanceTags = const [],
    this.textDescription,
    this.aiSummary,
    this.aiAttributeChanges = const [],
  });

  /// Mismo orden que la web: `autoGenerated` gana sobre todo, después puntos,
  /// después etiquetas, después texto.
  EvalType get type {
    if (autoGenerated) return EvalType.auto;
    if (rating != null) return EvalType.points;
    if (performanceTags.isNotEmpty) return EvalType.tags;
    if (textDescription != null && textDescription!.isNotEmpty) return EvalType.text;
    return EvalType.auto;
  }

  factory PeerEvaluation.fromMap(Map<String, dynamic> m) => PeerEvaluation(
        id: (m['id'] ?? '').toString(),
        evaluatorId: (m['evaluatorId'] ?? '').toString(),
        evaluatorDisplayName: m['evaluatorDisplayName'] as String?,
        evaluatorPhotoUrl: (m['evaluatorPhotoUrl'] ?? m['evaluatorPhotoURL']) as String?,
        isAnonymous: m['isAnonymous'] == true,
        autoGenerated: m['autoGenerated'] == true,
        identityRevealed: m['identityRevealed'] == true,
        identityRequestStatus: m['identityRequestStatus'] as String?,
        rating: (m['rating'] as num?)?.toDouble(),
        performanceTags: ((m['performanceTags'] as List?) ?? const [])
            .whereType<Map>()
            .map((e) => EvaluationTag.fromMap(Map<String, dynamic>.from(e)))
            .toList(),
        textDescription: m['textDescription'] as String?,
        aiSummary: m['aiSummary'] as String?,
        aiAttributeChanges: ((m['aiAttributeChanges'] as List?) ?? const [])
            .whereType<Map>()
            .map((e) => AttributeChange.fromMap(Map<String, dynamic>.from(e)))
            .toList(),
      );
}

class SelfEvaluationSummary {
  final int goals;
  final int assists;

  const SelfEvaluationSummary({this.goals = 0, this.assists = 0});

  factory SelfEvaluationSummary.fromMap(Map<String, dynamic> m) => SelfEvaluationSummary(
        goals: (m['goals'] as num?)?.toInt() ?? 0,
        assists: (m['assists'] as num?)?.toInt() ?? 0,
      );
}

class OvrUpdate {
  final int previousOvr;
  final int newOvr;

  const OvrUpdate({required this.previousOvr, required this.newOvr});

  double get change => (newOvr - previousOvr).toDouble();

  factory OvrUpdate.fromMap(Map<String, dynamic> m) => OvrUpdate(
        previousOvr: (m['previousOvr'] as num?)?.toInt() ?? 0,
        newOvr: (m['newOvr'] as num?)?.toInt() ?? 0,
      );
}

/// Un partido evaluado, con todo lo que el perfil muestra de él.
class MatchFeedback {
  final String matchId;
  final String title;
  final String? date;
  final String? locationName;
  final List<PeerEvaluation> peerEvaluations;
  final SelfEvaluationSummary? selfEvaluation;
  final OvrUpdate? ovrUpdate;

  const MatchFeedback({
    required this.matchId,
    required this.title,
    this.date,
    this.locationName,
    this.peerEvaluations = const [],
    this.selfEvaluation,
    this.ovrUpdate,
  });

  int get goals => selfEvaluation?.goals ?? 0;
  int get assists => selfEvaluation?.assists ?? 0;

  /// Promedio SOLO sobre las evaluaciones que traen nota. Dividir por todos los
  /// pares (incluyendo los de etiquetas o texto, que no tienen `rating`)
  /// hundía el promedio — era un bug real corregido en la web.
  double get avgRating {
    final withRating = peerEvaluations.where((e) => e.rating != null).toList();
    if (withRating.isEmpty) return 0;
    return withRating.map((e) => e.rating!).reduce((a, b) => a + b) / withRating.length;
  }

  /// Suma los cambios de atributos de las dos fuentes: los que calculó la IA
  /// y los `effects` de cada etiqueta. Mirar sólo `aiAttributeChanges` dejaba
  /// afuera las evaluaciones por etiquetas — también era un bug real.
  Map<String, int> get attributeDeltas {
    final acc = <String, int>{};
    for (final ev in peerEvaluations) {
      for (final c in ev.aiAttributeChanges) {
        acc[c.attribute] = (acc[c.attribute] ?? 0) + c.change;
      }
      for (final tag in ev.performanceTags) {
        for (final e in tag.effects) {
          acc[e.attribute] = (acc[e.attribute] ?? 0) + e.change;
        }
      }
    }
    return acc;
  }

  factory MatchFeedback.fromMap(Map<String, dynamic> m) {
    final self = m['selfEvaluation'];
    final ovr = m['ovrHistory'];
    return MatchFeedback(
      matchId: (m['matchId'] ?? '').toString(),
      title: (m['title'] ?? 'Partido').toString(),
      date: m['date'] as String?,
      locationName: m['locationName'] as String?,
      peerEvaluations: ((m['peerEvaluations'] as List?) ?? const [])
          .whereType<Map>()
          .map((e) => PeerEvaluation.fromMap(Map<String, dynamic>.from(e)))
          .toList(),
      selfEvaluation:
          self is Map ? SelfEvaluationSummary.fromMap(Map<String, dynamic>.from(self)) : null,
      ovrUpdate: ovr is Map ? OvrUpdate.fromMap(Map<String, dynamic>.from(ovr)) : null,
    );
  }
}

/// Los cuatro números de arriba del historial (modo compacto de la web).
class PlayerActivitySummary {
  final double avgRating;
  final int totalGoals;
  final int matchCount;
  final double totalOvrChange;

  const PlayerActivitySummary({
    required this.avgRating,
    required this.totalGoals,
    required this.matchCount,
    required this.totalOvrChange,
  });

  factory PlayerActivitySummary.from(List<MatchFeedback> matches) {
    final withRating = matches.where((m) => m.avgRating > 0).toList();
    return PlayerActivitySummary(
      avgRating: withRating.isEmpty
          ? 0
          : withRating.map((m) => m.avgRating).reduce((a, b) => a + b) / withRating.length,
      totalGoals: matches.fold(0, (s, m) => s + m.goals),
      matchCount: matches.length,
      totalOvrChange: matches.fold(0.0, (s, m) => s + (m.ovrUpdate?.change ?? 0)),
    );
  }
}
