'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { useFirestore, useUser } from '@/firebase';
import {
  collection, query, where, orderBy, getDocs,
  doc, getDoc, limit,
} from 'firebase/firestore';
import type { Evaluation, Match, OvrHistory, SelfEvaluation } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Loader2, Goal, Star, Calendar, Quote, Lock, MessageSquare,
  ChevronDown, CheckCircle2, Clock, Brain, Zap, Target,
  TrendingUp, TrendingDown, ChevronRight,
} from 'lucide-react';
import Link from 'next/link';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { requestIdentityRevelation, getPlayerEvaluationsAction } from '@/lib/actions/evaluation-actions';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { logger } from '@/lib/logger';
import { useToast } from '@/hooks/use-toast';
import {
  Collapsible, CollapsibleContent, CollapsibleTrigger,
} from '@/components/ui/collapsible';

// ─── Types ────────────────────────────────────────────────────────────────────

type PlayerMatchDebriefViewProps = {
  playerId: string;
  compact?: boolean;
};

type MatchFeedbackContext = {
  match: Match;
  selfEvaluation?: SelfEvaluation;
  peerEvaluations: Evaluation[];
  stats: {
    goals: number;
    assists: number;
    avgRating: number;
  };
  ovrUpdate?: {
    change: number;
    newOVR: number;
    oldOVR?: number;
  };
  attributeDeltas: Record<string, number>;
};

// ─── Constants ────────────────────────────────────────────────────────────────

const ATTR_LABELS: Record<string, string> = {
  pac: 'RIT', sho: 'TIR', pas: 'PAS', dri: 'REG', def: 'DEF', phy: 'FIS',
};

const ATTR_ORDER = ['pac', 'sho', 'pas', 'dri', 'def', 'phy'] as const;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function parseMatchDate(match: Match, selfEval?: SelfEvaluation, peerEvals?: Evaluation[]): Date | null {
  const rawDate = match.date || selfEval?.reportedAt || peerEvals?.[0]?.evaluatedAt;
  if (!rawDate) return null;
  if (typeof (rawDate as any).toDate === 'function') return (rawDate as any).toDate();
  const d = new Date(rawDate as string);
  return isNaN(d.getTime()) ? null : d;
}

function getMatchTitle(match: Match): string {
  if (match.title) return match.title;
  if (match.teams && match.teams.length >= 2) return `${match.teams[0].name} vs ${match.teams[1].name}`;
  return 'Partido Amistoso';
}

function TagIcon({ tag }: { tag: string }) {
  const lower = tag.toLowerCase();
  if (lower.includes('tact')) return <Brain className="h-3.5 w-3.5" />;
  if (lower.includes('veloc')) return <Zap className="h-3.5 w-3.5" />;
  if (lower.includes('gol')) return <Target className="h-3.5 w-3.5" />;
  return <Star className="h-3.5 w-3.5" />;
}

function getEvalType(ev: Evaluation): 'points' | 'tags' | 'text' | 'auto' {
  if (ev.autoGenerated) return 'auto';
  if (ev.rating !== undefined) return 'points';
  if (ev.performanceTags?.length) return 'tags';
  if (ev.textDescription) return 'text';
  return 'auto';
}

function buildAttributeDeltas(peerEvaluations: Evaluation[]): Record<string, number> {
  return peerEvaluations.reduce((acc, ev) => {
    for (const change of (ev.aiAttributeChanges ?? [])) {
      acc[change.attribute] = (acc[change.attribute] ?? 0) + change.change;
    }
    for (const tag of (ev.performanceTags ?? [])) {
      for (const effect of (tag.effects ?? [])) {
        acc[effect.attribute] = (acc[effect.attribute] ?? 0) + effect.change;
      }
    }
    return acc;
  }, {} as Record<string, number>);
}

function computeStats(
  peerEvaluations: Evaluation[],
  selfEval?: SelfEvaluation,
): { goals: number; assists: number; avgRating: number } {
  const ratingEvals = peerEvaluations.filter(e => e.rating !== undefined);
  return {
    goals: selfEval?.goals ?? 0,
    assists: selfEval?.assists ?? 0,
    avgRating: ratingEvals.length > 0
      ? ratingEvals.reduce((sum, e) => sum + e.rating!, 0) / ratingEvals.length
      : 0,
  };
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function HeroStat({ label, value, icon: Icon }: { label: string; value: string | number; icon?: React.ElementType }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-medium flex items-center gap-1">
        {Icon && <Icon className="h-3 w-3" />}
        {label}
      </span>
      <span className="text-2xl font-black font-mono tabular-nums text-foreground leading-none">{value}</span>
    </div>
  );
}

function AttributeTable({ deltas }: { deltas: Record<string, number> }) {
  return (
    <div className="space-y-1.5">
      {ATTR_ORDER.map(attr => {
        const delta = deltas[attr] ?? 0;
        return (
          <div key={attr} className="flex items-center gap-3 py-0.5">
            <span className="text-xs text-muted-foreground w-8 font-mono shrink-0">{ATTR_LABELS[attr]}</span>
            {delta !== 0 ? (
              <>
                <div className="flex-1 h-1 rounded-full bg-muted overflow-hidden">
                  <div
                    className={cn('h-full rounded-full', delta > 0 ? 'bg-emerald-500' : 'bg-red-500')}
                    style={{ width: `${Math.min(Math.abs(delta) * 25, 100)}%` }}
                  />
                </div>
                <span className={cn(
                  'text-xs font-bold w-7 text-right tabular-nums shrink-0',
                  delta > 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500',
                )}>
                  {delta > 0 ? '+' : ''}{delta}
                </span>
              </>
            ) : (
              <span className="text-xs text-muted-foreground/40 flex-1">─</span>
            )}
          </div>
        );
      })}
    </div>
  );
}

function PeerEvalList({
  peerEvals,
  playerId,
  onRequestIdentity,
  isOwner,
}: {
  peerEvals: Evaluation[];
  playerId: string;
  onRequestIdentity: (id: string) => void;
  isOwner: boolean;
}) {
  if (peerEvals.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-5 text-center space-y-1.5 opacity-60">
        <MessageSquare className="h-6 w-6 text-muted-foreground/50" />
        <p className="text-sm text-muted-foreground">Sin feedback de compañeros.</p>
      </div>
    );
  }

  return (
    <div>
      {peerEvals.map((ev, idx) => {
        const evalType = getEvalType(ev);

        // Auto-generated: simplified entry
        if (evalType === 'auto') {
          return (
            <div key={ev.id} className={cn('py-2.5', idx < peerEvals.length - 1 && 'border-b border-border/50')}>
              <p className="text-xs text-muted-foreground/50 italic">Evaluación automática</p>
            </div>
          );
        }

        // Compute per-eval tag effects for display
        const evalTagDeltas = evalType === 'tags'
          ? (ev.performanceTags ?? []).reduce((acc, tag) => {
            for (const effect of (tag.effects ?? [])) {
              acc[effect.attribute] = (acc[effect.attribute] ?? 0) + effect.change;
            }
            return acc;
          }, {} as Record<string, number>)
          : null;

        const typeBadge = evalType === 'points'
          ? <span className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground/60 px-1.5 py-0.5 rounded bg-muted/50">Puntos</span>
          : evalType === 'tags'
            ? <span className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground/60 px-1.5 py-0.5 rounded bg-muted/50">Tags</span>
            : <span className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground/60 px-1.5 py-0.5 rounded bg-muted/50">Texto</span>;

        return (
          <div key={ev.id} className={cn('py-3 flex items-start gap-3', idx < peerEvals.length - 1 && 'border-b border-border/50')}>
            {/* Avatar */}
            <Avatar className="h-9 w-9 shrink-0">
              {ev.identityRevealed && ev.evaluatorPhotoUrl ? (
                <AvatarImage src={ev.evaluatorPhotoUrl} />
              ) : ev.identityRevealed ? (
                <AvatarFallback className="bg-primary/20 text-primary font-bold text-xs">
                  {ev.evaluatorDisplayName?.charAt(0).toUpperCase() ?? '?'}
                </AvatarFallback>
              ) : (
                <AvatarFallback className="bg-muted text-muted-foreground">
                  <Lock className="h-3.5 w-3.5" />
                </AvatarFallback>
              )}
            </Avatar>

            {/* Content */}
            <div className="flex-1 min-w-0 space-y-1.5">
              {/* Name row */}
              <div className="flex items-center justify-between gap-2">
                <span className="text-sm font-medium flex items-center gap-1.5">
                  {ev.identityRevealed ? (
                    <span className="flex items-center gap-1 text-primary">
                      <CheckCircle2 className="h-3.5 w-3.5" />
                      {ev.evaluatorDisplayName || 'Identidad revelada'}
                    </span>
                  ) : (
                    'Anónimo'
                  )}
                  {typeBadge}
                </span>
                <div className="flex items-center gap-2 shrink-0">
                  {evalType === 'points' && typeof ev.rating === 'number' && (
                    <span className={cn(
                      'text-sm font-bold tabular-nums px-2 py-0.5 rounded-full',
                      ev.rating >= 8 ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' :
                        ev.rating >= 6 ? 'bg-amber-500/10 text-amber-600 dark:text-amber-400' :
                          'bg-slate-500/10 text-slate-500',
                    )}>
                      {ev.rating.toFixed(1)}
                    </span>
                  )}
                  {isOwner && !ev.identityRevealed && ev.evaluatorId !== 'AI' && (
                    ev.identityRequestStatus === 'pending' ? (
                      <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                        <Clock className="h-3 w-3" /> Enviada
                      </span>
                    ) : ev.identityRequestStatus === 'rejected' ? (
                      <span className="text-[10px] text-muted-foreground/60 italic">Rechazada</span>
                    ) : (
                      <button
                        onClick={() => onRequestIdentity(ev.id)}
                        className="text-[10px] font-semibold text-primary/80 hover:text-primary hover:underline flex items-center gap-1 transition-colors bg-primary/5 px-2 py-0.5 rounded-full"
                      >
                        <Lock className="h-3 w-3" /> Solicitar ID
                      </button>
                    )
                  )}
                </div>
              </div>

              {/* Tags */}
              {evalType === 'tags' && ev.performanceTags && ev.performanceTags.length > 0 && (
                <>
                  <div className="flex flex-wrap gap-1.5">
                    {ev.performanceTags.map((tag, i) => {
                      const tagName = typeof tag === 'string' ? tag : tag.name;
                      return (
                        <Badge key={i} variant="secondary" className="text-[11px] gap-1 px-2 py-0.5">
                          <TagIcon tag={tagName} />
                          {tagName}
                        </Badge>
                      );
                    })}
                  </div>
                  {evalTagDeltas && Object.values(evalTagDeltas).some(v => v !== 0) && (
                    <div className="flex flex-wrap gap-x-2 gap-y-0.5 mt-0.5">
                      {ATTR_ORDER.filter(a => (evalTagDeltas[a] ?? 0) !== 0).map(attr => (
                        <span key={attr} className={cn(
                          'text-[10px] font-mono font-semibold tabular-nums',
                          evalTagDeltas[attr] > 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500',
                        )}>
                          {ATTR_LABELS[attr]} {evalTagDeltas[attr] > 0 ? '+' : ''}{evalTagDeltas[attr]}
                        </span>
                      ))}
                    </div>
                  )}
                </>
              )}

              {/* Text eval: summary */}
              {evalType === 'text' && (ev.aiSummary || ev.textDescription) && (
                <p className="text-xs text-muted-foreground italic border-l-2 border-primary/20 pl-2">
                  "{ev.aiSummary ?? ev.textDescription!.slice(0, 120)}"
                </p>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function MatchCard({
  ctx,
  playerId,
  isFirst,
  onRequestIdentity,
  isOwner,
}: {
  ctx: MatchFeedbackContext;
  playerId: string;
  isFirst: boolean;
  onRequestIdentity: (id: string) => void;
  isOwner: boolean;
}) {
  const matchDate = parseMatchDate(ctx.match, ctx.selfEvaluation, ctx.peerEvaluations);
  const formattedDate = matchDate
    ? format(matchDate, "EEE d MMM yyyy", { locale: es })
    : 'Fecha desconocida';
  const displayTitle = getMatchTitle(ctx.match);
  const hasActiveDeltas = Object.values(ctx.attributeDeltas).some(v => v !== 0);

  const body = (
    <div className="space-y-4">
      {/* Stats row */}
      <div className="flex flex-wrap gap-2 text-sm">
        {ctx.ovrUpdate && (
          <span className={cn(
            'flex items-center gap-1 font-bold tabular-nums px-2.5 py-1 rounded-full text-xs',
            ctx.ovrUpdate.change >= 0
              ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
              : 'bg-red-500/10 text-red-500',
          )}>
            {ctx.ovrUpdate.change >= 0 ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}
            {ctx.ovrUpdate.change >= 0 ? '+' : ''}{ctx.ovrUpdate.change.toFixed(1)} OVR
          </span>
        )}
        {ctx.stats.avgRating > 0 && (
          <span className="flex items-center gap-1 px-2.5 py-1 rounded-full text-xs bg-muted/60 font-medium">
            <Star className="h-3.5 w-3.5 text-amber-500" />
            {ctx.stats.avgRating.toFixed(1)}
          </span>
        )}
        <span className="flex items-center gap-1 px-2.5 py-1 rounded-full text-xs bg-muted/60 font-medium">
          <Goal className="h-3.5 w-3.5 text-primary" />
          {ctx.stats.goals} {ctx.stats.goals === 1 ? 'gol' : 'goles'}
        </span>
        {ctx.stats.assists > 0 && (
          <span className="flex items-center gap-1 px-2.5 py-1 rounded-full text-xs bg-muted/60 font-medium">
            <Target className="h-3.5 w-3.5 text-primary" />
            {ctx.stats.assists} {ctx.stats.assists === 1 ? 'asist.' : 'asist.'}
          </span>
        )}
      </div>

      {/* Attributes table */}
      {hasActiveDeltas && (
        <>
          <Separator />
          <div>
            <p className="text-[10px] uppercase tracking-widest text-muted-foreground mb-2 font-semibold">Atributos</p>
            <AttributeTable deltas={ctx.attributeDeltas} />
          </div>
        </>
      )}

      {/* Chronicle */}
      {ctx.selfEvaluation?.personalChronicle && (
        <>
          <Separator />
          <blockquote className="border-l-2 border-primary/30 pl-3 italic text-sm text-muted-foreground">
            <Quote className="h-3.5 w-3.5 inline-block mr-1 opacity-50 -mt-1" />
            {ctx.selfEvaluation.personalChronicle}
          </blockquote>
        </>
      )}

      {/* Peer evaluations */}
      {(ctx.peerEvaluations.length > 0 || isFirst) && (
        <>
          <Separator />
          <div>
            <p className="text-[10px] uppercase tracking-widest text-muted-foreground mb-1 font-semibold flex items-center gap-1.5">
              <MessageSquare className="h-3 w-3" /> Votos del Vestuario
            </p>
            <PeerEvalList
              peerEvals={ctx.peerEvaluations}
              playerId={playerId}
              onRequestIdentity={onRequestIdentity}
              isOwner={isOwner}
            />
          </div>
        </>
      )}
    </div>
  );

  if (isFirst) {
    return (
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between gap-2">
            <div className="min-w-0">
              <CardTitle className="text-base leading-snug">{displayTitle}</CardTitle>
              <p className="text-xs text-muted-foreground mt-0.5 capitalize">{formattedDate}</p>
            </div>
            <Badge variant="outline" className="text-xs shrink-0">Último</Badge>
          </div>
        </CardHeader>
        <CardContent>{body}</CardContent>
      </Card>
    );
  }

  return (
    <Collapsible className="group">
      <div className="overflow-hidden rounded-xl border bg-card shadow-sm">
        <CollapsibleTrigger className="w-full text-left">
          <div className="px-4 py-3 flex items-center gap-3 bg-muted/30 hover:bg-muted/50 transition-colors">
            <span className="text-xs text-muted-foreground capitalize hidden sm:block w-32 shrink-0">
              {formattedDate}
            </span>
            <span className="text-xs text-muted-foreground capitalize sm:hidden shrink-0">
              {matchDate ? format(matchDate, 'd MMM', { locale: es }) : '—'}
            </span>
            <span className="font-semibold flex-1 truncate text-sm">{displayTitle}</span>
            {ctx.ovrUpdate && (
              <span className={cn(
                'font-bold tabular-nums text-xs shrink-0',
                ctx.ovrUpdate.change >= 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500',
              )}>
                {ctx.ovrUpdate.change >= 0 ? '+' : ''}{ctx.ovrUpdate.change.toFixed(1)}
              </span>
            )}
            {ctx.stats.avgRating > 0 && (
              <span className="text-xs font-bold tabular-nums shrink-0">{ctx.stats.avgRating.toFixed(1)}</span>
            )}
            <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0 transition-transform group-data-[state=open]:rotate-180" />
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="px-4 pb-4 pt-3 border-t border-border/40">
            {body}
          </div>
        </CollapsibleContent>
      </div>
    </Collapsible>
  );
}

// ─── Compact Skeleton ─────────────────────────────────────────────────────────

function CompactSkeleton() {
  return (
    <div className="space-y-4 animate-pulse">
      <div className="grid grid-cols-3 gap-4 px-1">
        {[1, 2, 3].map(i => <div key={i} className="h-10 rounded bg-muted" />)}
      </div>
      <div className="h-32 rounded-xl bg-muted" />
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export function PlayerMatchDebriefView({ playerId, compact }: PlayerMatchDebriefViewProps) {
  const firestore = useFirestore();
  const { user } = useUser();
  const { toast } = useToast();
  const [activities, setActivities] = useState<MatchFeedbackContext[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const isOwner = user?.uid === playerId;

  const handleRequestIdentity = async (evaluationId: string) => {
    try {
      const result = await requestIdentityRevelation(evaluationId);
      if (result.success) {
        toast({ title: 'Solicitud Enviada', description: 'Se notificó al compañero que querés saber su identidad.' });
        setActivities(prev => prev.map(activity => ({
          ...activity,
          peerEvaluations: activity.peerEvaluations.map(ev =>
            ev.id === evaluationId ? { ...ev, identityRequestStatus: 'pending' as const } : ev
          ),
        })));
      } else {
        toast({ variant: 'destructive', description: result.error || 'Error al solicitar identidad.' });
      }
    } catch {
      toast({ variant: 'destructive', description: 'Error de conexión.' });
    }
  };

  useEffect(() => {
    async function fetchActivity() {
      if (!firestore || !playerId) { setIsLoading(false); return; }
      setIsLoading(true);
      try {
        // 1. Fetch evaluations via Secure Server Action
        const { evaluations: allEvals, error: fetchError } = await getPlayerEvaluationsAction(playerId, user?.uid);

        if (fetchError) throw new Error(fetchError);

        if (allEvals.length === 0) { setActivities([]); setIsLoading(false); return; }

        // 2. Group evaluations by matchId
        const evalsByMatchId = allEvals.reduce((acc, ev) => {
          if (!acc[ev.matchId]) acc[ev.matchId] = [];
          acc[ev.matchId].push(ev);
          return acc;
        }, {} as Record<string, Evaluation[]>);

        const matchIds = Object.keys(evalsByMatchId);

        // 3. Fetch matches, ovrHistory, and selfEvaluations in parallel
        const matchPromises = matchIds.map(id => getDoc(doc(firestore, 'matches', id)));

        const ovrHistoryQuery = query(
          collection(firestore, 'players', playerId, 'ovrHistory'),
          where('matchId', 'in', matchIds.slice(0, 10)),
        );

        // selfEvaluations: for each matchId, query the subcollection
        const selfEvalPromises = matchIds.map(matchId =>
          getDocs(query(
            collection(firestore, 'matches', matchId, 'selfEvaluations'),
            where('playerId', '==', playerId),
            limit(1),
          ))
        );

        const [matchSnaps, ovrHistorySnap, ...selfEvalSnaps] = await Promise.all([
          Promise.all(matchPromises),
          matchIds.length > 0 ? getDocs(ovrHistoryQuery) : Promise.resolve({ docs: [] } as any),
          ...selfEvalPromises,
        ]);

        const matchesMap = new Map(
          matchSnaps.map(snap => [snap.id, { id: snap.id, ...snap.data() } as Match])
        );

        const ovrHistoryMap = new Map<string, OvrHistory>();
        ovrHistorySnap.docs.forEach((d: any) => {
          const data = d.data();
          ovrHistoryMap.set(data.matchId, data);
        });

        // Map matchId → selfEvaluation
        const selfEvalMap = new Map<string, SelfEvaluation>();
        matchIds.forEach((matchId, idx) => {
          const snap = selfEvalSnaps[idx];
          if (snap && snap.docs.length > 0) {
            const d = snap.docs[0];
            selfEvalMap.set(matchId, { id: d.id, ...d.data() } as SelfEvaluation);
          }
        });

        const contexts: MatchFeedbackContext[] = [];

        for (const matchId of matchIds) {
          const match = matchesMap.get(matchId);
          if (!match) continue;

          const evals = evalsByMatchId[matchId];
          const peerEvaluations = evals.filter((e: any) => e.evaluatorId !== playerId);

          // Use selfEvaluations subcollection for accurate goals/assists
          const selfEval = selfEvalMap.get(matchId);

          const stats = computeStats(peerEvaluations, selfEval);
          const attributeDeltas = buildAttributeDeltas(peerEvaluations);

          const ovrEntry = ovrHistoryMap.get(matchId);

          // Attach chronicle from selfEvaluation subcollection if available
          const selfEvalWithChronicle = selfEval
            ? { ...selfEval, personalChronicle: selfEval.personalChronicle }
            : undefined;

          contexts.push({
            match,
            selfEvaluation: selfEvalWithChronicle,
            peerEvaluations,
            stats,
            ovrUpdate: ovrEntry
              ? { change: ovrEntry.change, newOVR: ovrEntry.newOVR, oldOVR: ovrEntry.oldOVR }
              : undefined,
            attributeDeltas,
          });
        }

        // Sort by match date descending
        contexts.sort((a, b) => {
          const toMs = (d: any) =>
            d?.toDate ? d.toDate().getTime() : (d ? new Date(d).getTime() : 0);
          return toMs(b.match.date || 0) - toMs(a.match.date || 0);
        });

        setActivities(contexts);
      } catch (error: any) {
        logger.error('Failed to fetch player match debrief', error, { playerId });
      } finally {
        setIsLoading(false);
      }
    }
    fetchActivity();
  }, [firestore, playerId]);

  // ── Hero Stats ────────────────────────────────────────────────────────────────
  const heroStats = useMemo(() => {
    const withRating = activities.filter(a => a.stats.avgRating > 0);
    return {
      totalGoals: activities.reduce((s, a) => s + a.stats.goals, 0),
      avgRating: withRating.length > 0
        ? withRating.reduce((s, a) => s + a.stats.avgRating, 0) / withRating.length
        : 0,
      totalOvrChange: activities.reduce((s, a) => s + (a.ovrUpdate?.change ?? 0), 0),
      matchCount: activities.length,
    };
  }, [activities]);

  // ── Compact mode ──────────────────────────────────────────────────────────────
  if (compact) {
    if (isLoading) return <CompactSkeleton />;
    if (activities.length === 0) return null;

    const [latestMatch] = activities;
    return (
      <div className="space-y-4">
        {/* Hero stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 px-1">
          <HeroStat label="Rating Promedio" value={heroStats.avgRating > 0 ? heroStats.avgRating.toFixed(1) : '─'} icon={Star} />
          <HeroStat label="Goles Totales" value={heroStats.totalGoals} icon={Goal} />
          <HeroStat label="Partidos" value={heroStats.matchCount} icon={Calendar} />
          {heroStats.totalOvrChange !== 0 && (
            <div className="flex flex-col gap-0.5">
              <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-medium flex items-center gap-1">
                {heroStats.totalOvrChange > 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                Tendencia OVR
              </span>
              <span className={cn(
                'text-2xl font-black font-mono tabular-nums leading-none',
                heroStats.totalOvrChange > 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500',
              )}>
                {heroStats.totalOvrChange > 0 ? '+' : ''}{heroStats.totalOvrChange.toFixed(1)}
              </span>
            </div>
          )}
        </div>

        {/* Último partido */}
        <MatchCard
          ctx={latestMatch}
          playerId={playerId}
          isFirst
          onRequestIdentity={handleRequestIdentity}
          isOwner={isOwner}
        />

        {/* Link al historial completo */}
        <Link
          href={`/players/${playerId}/historial`}
          className="flex items-center justify-center gap-1 text-sm text-primary hover:underline"
        >
          Ver historial completo <ChevronRight className="h-3.5 w-3.5" />
        </Link>
      </div>
    );
  }

  // ── Loading / Empty ───────────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12">
        <Loader2 className="h-7 w-7 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (activities.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center space-y-3 text-muted-foreground">
        <Calendar className="h-10 w-10 opacity-30" />
        <p className="text-sm">Aún no hay partidos evaluados.</p>
      </div>
    );
  }

  const [latestMatch, ...previousMatches] = activities;

  return (
    <div className="space-y-6">
      {/* ── Hero Stats Row ──────────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 px-1">
        <HeroStat label="Rating Promedio" value={heroStats.avgRating > 0 ? heroStats.avgRating.toFixed(1) : '─'} icon={Star} />
        <HeroStat label="Goles Totales" value={heroStats.totalGoals} icon={Goal} />
        <HeroStat label="Partidos" value={heroStats.matchCount} icon={Calendar} />
        {heroStats.totalOvrChange !== 0 && (
          <div className="flex flex-col gap-0.5">
            <span className="text-[10px] uppercase tracking-widest text-muted-foreground font-medium flex items-center gap-1">
              {heroStats.totalOvrChange > 0 ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
              Tendencia OVR
            </span>
            <span className={cn(
              'text-2xl font-black font-mono tabular-nums leading-none',
              heroStats.totalOvrChange > 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500',
            )}>
              {heroStats.totalOvrChange > 0 ? '+' : ''}{heroStats.totalOvrChange.toFixed(1)}
            </span>
          </div>
        )}
      </div>

      {/* ── Latest Match ────────────────────────────────────────────────────── */}
      <MatchCard
        ctx={latestMatch}
        playerId={playerId}
        isFirst
        onRequestIdentity={handleRequestIdentity}
        isOwner={isOwner}
      />

      {/* ── Previous Matches ─────────────────────────────────────────────────── */}
      {previousMatches.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider px-1">
            Partidos Anteriores
          </h3>
          <div className="space-y-2">
            {previousMatches.map(ctx => (
              <MatchCard
                key={ctx.match.id}
                ctx={ctx}
                playerId={playerId}
                isFirst={false}
                onRequestIdentity={handleRequestIdentity}
                isOwner={isOwner}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
