// File generated by Antigravity for Pateá Mobile
// Firebase project: mil-disculpis
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAes7EVn8hQswS8XgvDMJfN6U4IT_ZL_WY',
    appId: '1:5614567933:web:6d7b7dde5f994c36861994',
    messagingSenderId: '5614567933',
    projectId: 'mil-disculpis',
    authDomain: 'mil-disculpis.firebaseapp.com',
    storageBucket: 'mil-disculpis.firebasestorage.app',
    measurementId: 'G-56F70EMSVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAes7EVn8hQswS8XgvDMJfN6U4IT_ZL_WY',
    appId: '1:5614567933:android:6d7b7dde5f994c36861994',
    messagingSenderId: '5614567933',
    projectId: 'mil-disculpis',
    storageBucket: 'mil-disculpis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAes7EVn8hQswS8XgvDMJfN6U4IT_ZL_WY',
    appId: '1:5614567933:ios:6d7b7dde5f994c36861994',
    messagingSenderId: '5614567933',
    projectId: 'mil-disculpis',
    storageBucket: 'mil-disculpis.firebasestorage.app',
    iosBundleId: 'com.patea.app',
  );
}
